# Generated by Django 5.1 on 2024-08-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
