# Generated by Django 5.1 on 2024-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
